# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks


target 'AlamofireDemo' do
use_frameworks!

  # Pods for AlamofireDemo

  target 'AlamofireDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Alamofire'

end
